FROM ruby:2.5.1

ENV LANG C.UTF-8

RUN apt-get update -qq && apt-get install -y       build-essential       postgresql-client

WORKDIR /tmp
COPY Gemfile* /tmp/
RUN bundle install

CMD echo Nothing to do here
